from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Dict, Any
import re
from datetime import datetime, timezone

EVM_ADDRESS_REGEX = re.compile(r"^0x[a-fA-F0-9]{40}$")
SIGNATURE_REGEX = re.compile(r"^0x[a-fA-F0-9]{130}$")

class EIP712Domain(BaseModel):
    name: str = Field(..., description="The name of the signing domain (e.g., 'AgentPaymentsProtocol')")
    version: str = Field(..., description="The current security version of the domain specification")
    chainId: int = Field(..., description="The target EVM Chain ID")
    verifyingContract: str = Field(..., description="The address of the verification smart contract instance")

    @field_validator("verifyingContract")
    @classmethod
    def validate_evm_address(cls, value: str) -> str:
        if not EVM_ADDRESS_REGEX.match(value):
            raise ValueError("Invalid contract verification target format. Must be a valid 0x EVM address.")
        return value

class PaymentMandateMessage(BaseModel):
    agentId: str = Field(..., description="Unique identifier mapping of the executing automated agent")
    userAddress: str = Field(..., description="The public wallet address of the authorizing asset controller")
    vaultAddress: str = Field(..., description="The address of the CompliantYieldVault contract target")
    maxAmountLimit: int = Field(..., gt=0, description="The maximum individual capital allowance denominated in base units")
    expirationTimestamp: int = Field(..., description="Unix timestamp threshold indicating when the mandate token expires")
    nonce: int = Field(..., ge=0, description="Anti-replay identifier matched to the user's database records")

    @field_validator("userAddress", "vaultAddress")
    @classmethod
    def validate_addresses(cls, value: str) -> str:
        if not EVM_ADDRESS_REGEX.match(value):
            raise ValueError("Provided parameter string is not a cryptographically valid EVM address.")
        return value

    @field_validator("expirationTimestamp")
    @classmethod
    def validate_future_expiry(cls, value: int) -> int:
        current_time = int(datetime.now(timezone.utc).timestamp())
        if value <= current_time:
            raise ValueError("Mandate initialization rejection: defined authorization window has already expired.")
        return value

class AgentPaymentMandateRequest(BaseModel):
    domain: EIP712Domain = Field(..., description="EIP-712 domain block defining platform execution limits")
    message: PaymentMandateMessage = Field(..., description="Structured mandate data block containing the agent permissions")
    signature: str = Field(..., description="The cryptographic Elliptic Curve signature (r, s, v) generated by the user's private key")

    @field_validator("signature")
    @classmethod
    def validate_signature_hex(cls, value: str) -> str:
        if not SIGNATURE_REGEX.match(value):
            raise ValueError("Malformed signature format. Must be a 65-byte hex-encoded string containing a '0x' prefix.")
        return value
